# Generated by Django 4.2.3 on 2023-09-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persons',
            table='persons',
        ),
    ]
